name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9, pypy3]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: tox -e scripts,py

  lint:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - run: tox -e lint

  docs:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./docs/requirements-docs.txt
      - run: tox -e docs
